### ISSUE TITLE
[Bug]:关于psi小刀交互问题

### ISSUE THREAD

**Issue by eciv-oN** [Y-Xiao233/Compact-World-Expert#1]
### Modpack Version

0.0.35

### Describe your issue

尝试将无耐久的psi小刀放到砧板上会提示没有魔源支持，在把小刀取下来前无法与大部分方块正常交互

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Y-Xiao233** [comment]
Okay, fixed in v0.0.4
