### ISSUE TITLE
[Bug]:<title> 粗金块可以在熔炉里烧成金块

### ISSUE THREAD

**Issue by locomotive488** [Y-Xiao233/Compact-World-Expert#10]
### Modpack Version

Beta 1.1.0

### Describe your issue

粗金块可以在熔炉里烧成金块
![金块bug](https://github.com/Y-Xiao233/Compact-World-Expert/assets/165468576/76db6267-814a-4e9a-9de7-ab54202c5b29)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Y-Xiao233** [comment]
Beta v1.2.0修复
