### ISSUE TITLE
[Bug]:1.2版本未添加法术羊皮纸及抄写台配方

### ISSUE THREAD

**Issue by Me-lac** [Y-Xiao233/Compact-World-Expert#11]
### Modpack Version

beta 1.2

### Describe your issue

如题 1.2并没有修改法术抄写台以及羊皮纸的配方 在无红石的情况下较难做出施法自动化

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Y-Xiao233** [comment]
Beta v1.3.0修复
