### ISSUE TITLE
[Mod Suggestion]:加个Reaper

### ISSUE THREAD

**Issue by along-go** [Y-Xiao233/Compact-World-Expert#12]
### URL

https://www.curseforge.com/minecraft/mc-mods/reaper

### Why would you like the mod added?

感觉发电方式有点单一，这个改一改可以拿来过渡，顺便也可以配合刷怪笼实现一些妙招（

**Comment by Y-Xiao233** [comment]
我尝试加入了这个mod，但是这个mod导致了游戏的崩溃，这意味着我得删除已有的至少1个mod，甚至更多，以此来使其适配本整合包，这明显是不值得的

**Comment by Y-Xiao233** [comment]
我尝试加入了这个mod，但是这个mod导致了游戏的崩溃，这意味着我得删除已有的至少1个mod，甚至更多，以此来使其适配本整合包，这明显是不值得的
