### ISSUE TITLE
[Bug]:电解分离器无法合成

### ISSUE THREAD

**Issue by YocyCraft** [Y-Xiao233/Compact-World-Expert#13]
### Modpack Version

1.2.0

### Describe your issue

 电解分离器需要电解核心，电解核心需要锇粉，但是锇粉在游戏内没有合成配方。

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Y-Xiao233** [comment]
Beta v1.3.0修复
