### ISSUE TITLE
[Bug]:offering table not giving crafted items

### ISSUE THREAD

**Issue by funash1998** [Y-Xiao233/Compact-World-Expert#15]
### Modpack Version

1.19.2

### Describe your issue

the offering table isn't giving crafted items to be collected by item collector

### Have you modified the modpack?

no

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Y-Xiao233** [comment]
Do you place this structure in a compressed space? If so, there will be no crafting items. Please place it in the overworld. If you place it in the overworld, try adjusting the item collection range

**Comment by funash1998** [comment]
yes i placed the offering table in a compressed space  how do i place it in the overworld

**Comment by Y-Xiao233** [comment]
When you first entered the game, the place you were in was the overworld

**Comment by funash1998** [comment]
its working thank you
