### ISSUE TITLE
[Bug]:<title> 自然祭坛无法合成

### ISSUE THREAD

**Issue by dsgjhs121** [Y-Xiao233/Compact-World-Expert#16]
### Modpack Version

Beta v1.3.0

### Describe your issue

自然祭坛无法合成ae的电路板和硅板

### Have you modified the modpack?

Yes

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Y-Xiao233** [comment]
请把自然祭坛放置在主世界在进行合成,而不是在压缩空间进行合成

**Comment by dsgjhs121** [comment]
抱歉我没仔细看任务
