### ISSUE TITLE
在创建新世界时旧世界被覆盖

### ISSUE THREAD

**Issue by whaterrow** [Y-Xiao233/Compact-World-Expert#17]
### Modpack Version

Beta 1.3.0

### Describe your issue

在创建新世界（存档）时如果使用了与已有世界（存档）相同的世界名（存档名），旧的世界（存档）会被覆盖而非生成一个名为××××（1）的新世界（存档）

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Y-Xiao233** [comment]
此问题为模组lockdown的问题,无法解决(
