### ISSUE TITLE
逻辑压印模板无法复制

### ISSUE THREAD

**Issue by whaterrow** [Y-Xiao233/Compact-World-Expert#18]
### Modpack Version

Beta 1.3.0

### Describe your issue

应用能源的逻辑压印模板不能在压印器中通过盖亚魂粒复制，该合成会消耗原有模板导致逻辑压印模板等同于未被复制，测试发现其他压印模板未出现该Bug

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Y-Xiao233** [comment]
Beta v1.4.0修复
