### ISSUE TITLE
psi的挖掘启动式不能挖掘自定义机器

### ISSUE THREAD

**Issue by whaterrow** [Y-Xiao233/Compact-World-Expert#19]
### Modpack Version

Beta 1.3.0

### Describe your issue

psi的挖掘启动式不能挖掘来源为Compact World Expert的自定义机器。

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Y-Xiao233** [comment]
不使用就行了,如果让psi可以挖的话会导致新生魔艺法术书破坏自定义机器没有掉落物
