### ISSUE TITLE
[Bug]: Spirit 压缩灵魂粉块(compressed soul powder block)破壞後不會掉落

### ISSUE THREAD

**Issue by BoxZen** [Y-Xiao233/Compact-World-Expert#21]
### Modpack Version

Beta v1.4.0

### Describe your issue

於遊戲中破壞压缩灵魂粉块後不會掉落。
我在只有 spirit 的遊戲中測試過，在 Spirit v2.2.0 中，压缩粉塊破壞皆不會掉落，當我把版本更新為 v2.2.7 ，破壞後就會掉落了。

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Y-Xiao233** [comment]
Spirit v2.2.0以上版本mod内置语言文件有问题，故此我选择了这个版本，我会在下个版本的时候尝试使用kubejs给这个方块添加一个战利品表

**Comment by Y-Xiao233** [comment]
Beta v1.5.0修复
