### ISSUE TITLE
[Bug]:<流体储罐不能直接交互流体> 

### ISSUE THREAD

**Issue by whaterrow** [Y-Xiao233/Compact-World-Expert#23]
### Modpack Version

beta 1.4.0

### Describe your issue

Beta1.4.0 的更新中提到了现在在生存模式下已可以与流体储罐直接交互流体，但我在进行德格米护符合成的过程中手持熔岩桶对流体储罐右键，熔岩流体短暂得出现在被右键的面所对的位置，随后立即消失，但流体储罐内并未增加流体。

https://github.com/Y-Xiao233/Compact-World-Expert/assets/112762628/8a941007-56ec-4e85-a90b-d44799469823

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by whaterrow** [comment]
在合成完毕后置物台中的物品会正常消耗，但物品模型不会消失，流体储罐中的流体则仍然保留，并且现在使用空桶对流体储罐右键会在不消耗储罐内流体的情况下在储罐对应面生成一桶该流体，测试发现几乎所有流体都可以刷

**Comment by whaterrow** [comment]
Uploading Compact World_ Expert Beta v1.4.0 2024-06-21 15-10-55.mp4…

**Comment by whaterrow** [comment]
https://github.com/Y-Xiao233/Compact-World-Expert/assets/112762628/e2eebf0e-4673-46d4-a41a-bffc319be2d2

**Comment by Y-Xiao233** [comment]
经测试,以上两个问题应该都为压缩空间所导致,具体原因暂时未知

**Comment by Y-Xiao233** [comment]
Beta v1.6.0修改至这些操作只能在主世界进行
