### ISSUE TITLE
[Bug]: 任務所需物品未設定匹配NBT

### ISSUE THREAD

**Issue by EvanHsieh0415** [Y-Xiao233/Compact-World-Expert#24]
### Modpack Version

Beta 1.4.0

### Describe your issue

任務所需物品未設定匹配NBT
舉例來說：
![圖片](https://github.com/Y-Xiao233/Compact-World-Expert/assets/74277414/36b5d810-3dc6-47d6-af0b-f86f68a9ae86)![圖片](https://github.com/Y-Xiao233/Compact-World-Expert/assets/74277414/a22e67ac-e698-447b-b2a7-839c6c8aad2d)
應當為
![圖片](https://github.com/Y-Xiao233/Compact-World-Expert/assets/74277414/322081b5-8bf2-479a-935f-426dc2f4d73f)
或將此物品加入 `itemfilters:match_nbt` 物品標籤中

### Have you modified the modpack?

Yes

### User Modifications

RTLite - 翻譯模組

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Y-Xiao233** [comment]
我会在下版本修复~

**Comment by Y-Xiao233** [comment]
Beta v1.6.0修复
