### ISSUE TITLE
[Bug]:大水车应力与任务描述不符

### ISSUE THREAD

**Issue by eciv-oN** [Y-Xiao233/Compact-World-Expert#3]
### Modpack Version

0.0.5

### Describe your issue

大水车任务描述为1024su，实际仅512su

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Y-Xiao233** [comment]
需要删除saves/存档名/serverconfig/create-server.toml后重启游戏
