### ISSUE TITLE
[General Suggestion]:<精准投掷器不能合成> 

### ISSUE THREAD

**Issue by whaterrow** [Y-Xiao233/Compact-World-Expert#33]
### Describe your suggestion

精准投掷器使用了被关闭合成的压缩圆石,我希望它至少是可合成的,而不是根本无法使用

### Why would you like this added/changed?

自动化思路被打断被迫改用路由器有感

**Comment by Y-Xiao233** [comment]
?什么东西的自动化非得用精准投掷器
