### ISSUE TITLE
[Bug]: Fake fluid tank 

### ISSUE THREAD

**Issue by Marsshiii** [Y-Xiao233/Compact-World-Expert#34]
### Modpack Version

Beta v1.6.0-hotfix

### Describe your issue

I follow every steps for using the fluind tanking crafting thing 
and it's not working for some reason 
Here is a pic of the things i've done. Using the dominion wand on it doesn't do anything 

![image_2024-06-25_062511789](https://github.com/Y-Xiao233/Compact-World-Expert/assets/126317289/f20b7643-8599-4544-b91a-839657c07b22)

### Have you modified the modpack?

Yes

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Marsshiii** [comment]
I found the reason but might be good to precise. It can only be use on your main room. Not in compact machine

**Comment by Y-Xiao233** [comment]
Yep,because this crafting will cause bugs in compressed world.So, in the Beta v1.6.0 update, it was restricted that it can only be crafting in the overworld.You can see this in the update log, or you can learn about it by "shifte + right click" on the fluid tank with empty hand in the game.
