### ISSUE TITLE
[Bug]:机械炸锅和融化器识别不了加了吸管的燃烧室

### ISSUE THREAD

**Issue by fenglbl** [Y-Xiao233/Compact-World-Expert#36]
### Modpack Version

1.6.0及之前版本

### Describe your issue

机械炸锅和熔化器识别不了加了吸管的燃烧室

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Y-Xiao233** [comment]
mod原因无法修复(<_<
