### ISSUE TITLE
[Bug]: Compressed Andesite Can Not be Crafted Back Into 9 Andesite 

### ISSUE THREAD

**Issue by TimeBender25** [Y-Xiao233/Compact-World-Expert#38]
### Modpack Version

v2.3.0

### Describe your issue

It is possible to compress andesite into a Compressium storage block:
![image](https://github.com/user-attachments/assets/43a06d78-ab97-402b-aedd-f823f5f18f7f)
However, it becomes impossible to craft it back into the 9 andesite it was made from:
![image](https://github.com/user-attachments/assets/0df96f60-579f-4f48-924c-28de71ea9b6f)

I am led to believe this is accidental, as cobblestone correctly crafts both ways:
![image](https://github.com/user-attachments/assets/7288901c-8ae4-4e06-9912-93f0634adee8)
![image](https://github.com/user-attachments/assets/0120bff1-c4ab-4817-9d63-cfeb670c5a2a)

### Have you modified the modpack?

Yes

### User Modifications

Added [EMI](https://modrinth.com/mod/emi/version/1.1.18+1.19.2+forge), as well as [EMI: Create Schematics](https://modrinth.com/mod/emi-create-schematics/version/1.0.0). Did _not_ remove REI, as EMI can communicate with it for compatibility reasons.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Y-Xiao233** [comment]
This may be a bug in Compressium, I will add this recipe in the next version.
