### ISSUE TITLE
[General Suggestion]:物品配方相关

### ISSUE THREAD

**Issue by eciv-oN** [Y-Xiao233/Compact-World-Expert#4]
### Describe your suggestion

无法制作或阶段错误的物品
精妙存储 包装带（粘液球）
精妙存储 存储工具
精妙存储 存储链接
AE2 切割刀

### Why would you like this added/changed?

物品无法制作或阶段错误（

**Comment by Y-Xiao233** [comment]
已在v0.0.6修复
