### ISSUE TITLE
[Bug]: 修改错误的物品描述

### ISSUE THREAD

**Issue by ailixiyaX** [Y-Xiao233/Compact-World-Expert#7]
### Modpack Version

all version

### Describe your issue

1.模组物品有时会有自带的物品描述，但修改了后这些描述将不起作用，可自定义描述，不然将起到一定误导作用（点名某粉末）
2.部分描述出现错误，如压缩粉末有两行完全相同的描述
![Uploading a935200ac42ddc591dae3ef1278f8c03.png…]()

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by ailixiyaX** [comment]
这些问题其实无伤大雅（1有任务可以看），所以可延后修复

**Comment by Y-Xiao233** [comment]
1.我不会删物品原来的描述（
2.关于部分描述有两行的问题，他貌似是rei导致的，我将会在下个版本改为jei

**Comment by ailixiyaX** [comment]
awa

**Comment by Y-Xiao233** [comment]
已在v0.0.6修复
