### ISSUE TITLE
[Bug]:离心机上面放流体抽屉导致崩溃

### ISSUE THREAD

**Issue by YocyCraft** [Y-Xiao233/Compact-World-Expert#9]
### Modpack Version

0.1.0

### Describe your issue

崩溃之后每次重新进存档都立刻崩溃

[crash-2024-06-09_17.18.42-server.txt](https://github.com/user-attachments/files/15751315/crash-2024-06-09_17.18.42-server.txt)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Y-Xiao233** [comment]
这或许是mod的bug，我只能在下个版本的时候在玩家放置这个方块的时候取消这个时事件,
